version: '3'

services:

  client:
    container_name: client
    build: ./client
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/usr/src/app
    command: [sh, -c, "cd nuxt/ && npm run dev"]

  api:
    container_name: api
    build: ./api
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ./api:/code
    command: python manage.py runserver 0.0.0.0:8000

